### ISSUE TITLE
Add a button to each color to quick open edit dialog "Choose color"

### ISSUE THREAD

**Issue by Kolyall** [shiraji/color-manager#34]
Add a button to each color to quick open edit dialog "Choose a color"
![14 09](https://cloud.githubusercontent.com/assets/3495165/18504812/eb1309e2-7a6c-11e6-8f2d-ac77fad31005.png)

**Comment by shiraji** [comment]
Thanks! I'm just working on this one. Related issue is #2

**Comment by shiraji** [comment]
Release as https://github.com/shiraji/color-manager/releases/tag/1.1.2
